#!/usr/bin/env python3
"""
Kalman Filter Test Data Generator and Plotter
Generates test data for ASIC verification and plots results.

Usage:
  python3 kf_gen_test.py <num_iterations>     # Generate test data
  python3 kf_gen_test.py --plot               # Plot results after simulation

Outputs:
  - truth.txt:        Ground truth positions (one value per line)
  - measurements.txt: Noisy measurements (one value per line)
  - kf_expected.txt:  Expected KF outputs after each iteration (x1, x2 per line)
  - kf_asic.txt:      ASIC outputs (generated by testbench)
  - kf_results.png:   Comparison plot (when --plot is used)
"""

import numpy as np
import sys
import os

def run_kf_iteration(x, P, Phi, Q, H, R, y):
    """Run one KF iteration (predict + update) per paper Eq. 3-7"""
    x_pred = Phi @ x
    P_pred = Phi @ P @ Phi.T + Q
    S = H @ P_pred @ H.T + R
    K = P_pred @ H.T / S
    innovation = y - H @ x_pred
    x_upd = x_pred + K * innovation
    I = np.eye(len(x))
    P_upd = (I - K @ H) @ P_pred
    return x_upd, P_upd

def generate_test_data(num_iters):
    """Generate test data files"""
    np.random.seed(42)

    # Parameters
    dt = 0.1
    true_x0, true_v0 = 0.0, 0.03
    measurement_noise_std, process_noise_std = 0.3, 0.1

    # KF matrices
    Phi = np.array([[1.0, dt], [0.0, 1.0]])
    Q = np.array([[0.01, 0.0], [0.0, 0.01]])
    H = np.array([[1.0, 0.0]])
    R = np.array([[0.1]])

    # Initial state
    x_kf = np.array([[0.0], [0.03]])
    P_kf = np.array([[1.0, 0.0], [0.0, 1.0]])

    # Generate ground truth
    true_positions = []
    pos, vel = true_x0, true_v0
    for _ in range(num_iters):
        true_positions.append(pos)
        pos += vel * dt + np.random.normal(0, process_noise_std)
        vel += np.random.normal(0, process_noise_std * 0.1)

    # Add measurement noise
    measurements = [p + np.random.normal(0, measurement_noise_std) for p in true_positions]

    # Run KF
    kf_outputs = []
    for i in range(num_iters):
        y = np.array([[measurements[i]]])
        x_kf, P_kf = run_kf_iteration(x_kf, P_kf, Phi, Q, H, R, y)
        kf_outputs.append((x_kf[0, 0], x_kf[1, 0]))

    # Export files
    with open("truth.txt", "w") as f:
        for val in true_positions:
            f.write(f"{val:.6f}\n")

    with open("measurements.txt", "w") as f:
        for val in measurements:
            f.write(f"{val:.6f}\n")

    with open("kf_expected.txt", "w") as f:
        for x1, x2 in kf_outputs:
            f.write(f"{x1:.6f} {x2:.6f}\n")

    print(f"Generated {num_iters} iterations of test data:")
    print(f"  truth.txt        - {num_iters} ground truth positions")
    print(f"  measurements.txt - {num_iters} noisy measurements")
    print(f"  kf_expected.txt  - {num_iters} expected KF outputs (x1 x2)")
    print(f"\nFinal expected values:")
    print(f"  x1 (position) = {kf_outputs[-1][0]:.6f}")
    print(f"  x2 (velocity) = {kf_outputs[-1][1]:.6f}")

def plot_results():
    """Plot comparison of truth, measurements, expected KF, and ASIC results"""
    import matplotlib.pyplot as plt

    # Load data
    if not os.path.exists("truth.txt"):
        print("ERROR: truth.txt not found. Run test first.")
        sys.exit(1)

    truth = np.loadtxt("truth.txt")
    measurements = np.loadtxt("measurements.txt")
    kf_expected = np.loadtxt("kf_expected.txt")

    # Check for ASIC results
    has_asic = os.path.exists("kf_asic.txt")
    if has_asic:
        kf_asic = np.loadtxt("kf_asic.txt")
    else:
        print("Note: kf_asic.txt not found, plotting without ASIC data")

    n = len(truth)
    iters = np.arange(1, n + 1)

    # Create figure with 3 subplots
    fig, (ax1, ax2, ax3) = plt.subplots(3, 1, figsize=(12, 10))

    # --- Position (x1) Plot ---
    ax1.plot(iters, measurements, '-', linewidth=1, alpha=0.7, color='gray', label='Measurements (noisy)')
    ax1.plot(iters, truth, '-', linewidth=2, color='green', label='Ground Truth')
    ax1.plot(iters, kf_expected[:, 0], '--', linewidth=2, color='blue', label='Python KF')
    if has_asic:
        ax1.plot(iters, kf_asic[:, 0], ':', linewidth=2, color='red', label='ASIC KF')

    ax1.set_xlabel('Iteration')
    ax1.set_ylabel('Position (x1)')
    ax1.set_title('Position Estimation (x1)')
    ax1.legend(loc='best')
    ax1.grid(True, alpha=0.3)

    # --- Velocity (x2) Plot ---
    ax2.plot(iters, kf_expected[:, 1], '--', linewidth=2, color='blue', label='Python KF')
    if has_asic:
        ax2.plot(iters, kf_asic[:, 1], ':', linewidth=2, color='red', label='ASIC KF')

    ax2.set_xlabel('Iteration')
    ax2.set_ylabel('Velocity (x2)')
    ax2.set_title('Velocity Estimation (x2) - Inferred from position changes')
    ax2.legend(loc='best')
    ax2.grid(True, alpha=0.3)

    # --- Error Plot ---
    raw_err = np.abs(measurements - truth)
    kf_err = np.abs(kf_expected[:, 0] - truth)
    ax3.plot(iters, raw_err, '-', linewidth=1, alpha=0.7, color='gray', label='Raw Measurement Error')
    ax3.plot(iters, kf_err, '-', linewidth=2, color='blue', label='Python KF Error')
    if has_asic:
        asic_err = np.abs(kf_asic[:, 0] - truth)
        ax3.plot(iters, asic_err, '--', linewidth=2, color='red', label='ASIC KF Error')

    ax3.set_xlabel('Iteration')
    ax3.set_ylabel('Absolute Error')
    ax3.set_title('Position Estimation Error')
    ax3.legend(loc='best')
    ax3.grid(True, alpha=0.3)

    plt.tight_layout()

    # Save figure
    plt.savefig('kf_results.png', dpi=150)
    print(f"\nPlot saved: kf_results.png")

    # Print statistics
    print(f"\n{'='*60}")
    print("Statistics")
    print('='*60)
    print(f"Number of iterations: {n}")
    print(f"\nPosition (x1) RMSE:")
    print(f"  Raw Measurement: {np.sqrt(np.mean(raw_err**2)):.6f}")
    print(f"  Python KF:       {np.sqrt(np.mean(kf_err**2)):.6f}")
    if has_asic:
        print(f"  ASIC KF:         {np.sqrt(np.mean(asic_err**2)):.6f}")
        asic_vs_py = np.abs(kf_asic[:, 0] - kf_expected[:, 0])
        print(f"  ASIC vs Python:  {np.sqrt(np.mean(asic_vs_py**2)):.6f}")
    print(f"\nNoise Reduction: {(1 - np.sqrt(np.mean(kf_err**2)) / np.sqrt(np.mean(raw_err**2))) * 100:.1f}%")

    # Show plot
    plt.show()

def main():
    if len(sys.argv) != 2:
        print("Usage:")
        print("  python3 kf_gen_test.py <num_iterations>  # Generate test data")
        print("  python3 kf_gen_test.py --plot            # Plot results")
        sys.exit(1)

    if sys.argv[1] == "--plot":
        plot_results()
    else:
        num_iters = int(sys.argv[1])
        generate_test_data(num_iters)

if __name__ == "__main__":
    main()
